/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticketingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/**
 *
 * @author Mila
 */
public class LogInAdmin extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    

    /**
     * Creates new form LogInAdmin
     */
    public LogInAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.    
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJlabel = new javax.swing.JLabel();
        text1Jlabel = new javax.swing.JLabel();
        text2Jlabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        text3Jlabel = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        main2label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 820));

        text1Jlabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        text1Jlabel.setText("Log In First");
        getContentPane().add(text1Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 330, 60));

        text2Jlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text2Jlabel.setText("Username");
        getContentPane().add(text2Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 40));

        username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 260, 210, 40));

        text3Jlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text3Jlabel.setText("Password");
        getContentPane().add(text3Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 150, 30));

        passwordfield.setText("jPasswordField1");
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 190, 30));

        loginbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginbutton.setText("Log In");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 310, 50));

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("Back To Start");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 310, 50));

        main2label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainticketingsystem/3.jpg"))); // NOI18N
        getContentPane().add(main2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        
        String sql = "select * from admindetails where ((username = ? ) and passwordfield = ?)";
        
      try
      {
            System.out.println("  yaay :3 ...");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=9803;" +
            "databaseName=TrainTicketingSystem;";
            
            con = DriverManager.getConnection(connectionUrl);
            pst = con.prepareStatement(sql);
            pst.setString(1,username.getText());
            pst.setString(2,passwordfield.getText());
            rs = pst.executeQuery();
            if (rs.next())
            {
                JOptionPane.showMessageDialog(null, "Username and Password has matched!!!");
                 Admindetails adt = new Admindetails();
                  adt.setVisible(true);
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "Username and Password has not matched");
            }
      }
      
      catch(Exception e)
              {
                  JOptionPane.showMessageDialog(null, e);
              }
        
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
          Startpage st = new Startpage();
          st.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel main2label;
    private javax.swing.JLabel mainJlabel;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel text1Jlabel;
    private javax.swing.JLabel text2Jlabel;
    private javax.swing.JLabel text3Jlabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
