/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticketingsystem;

import trainticketingsystem.otherjavas.Passengerdetail;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trainticketingsystem.otherjavas.Operationpassenger;

/**
 *
 * @author Mila
 */
public class Passengerdetails extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Passengerdetails
     */
     Operationpassenger ope = new Operationpassenger();
    ArrayList <Passengerdetails> PassengeretailsList=new ArrayList <Passengerdetails>();//changes done here 
    public Passengerdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainlabel = new javax.swing.JLabel();
        textlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        IDlabel = new javax.swing.JLabel();
        IDtext = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        updatebitton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        viewbutton = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        trainidtext = new javax.swing.JTextField();
        text3 = new javax.swing.JLabel();
        numberofbookedtext = new javax.swing.JTextField();
        main2label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        textlabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textlabel.setText("Passenger Details");
        getContentPane().add(textlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 34, 380, 60));

        namelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelabel.setText("Passenger Name");
        getContentPane().add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 178, 170, 30));
        getContentPane().add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 330, 70));

        IDlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IDlabel.setText("Passenger ID");
        getContentPane().add(IDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, 20));
        getContentPane().add(IDtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 350, 70));

        addbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 220, 60));

        updatebitton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updatebitton.setText("Update");
        updatebitton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebittonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebitton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 263, 220, 60));

        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 220, 60));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 220, 60));

        viewbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewbutton.setText("View");
        viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(viewbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 423, 220, 60));

        text2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text2.setText("Train ID");
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 80, 30));
        getContentPane().add(trainidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 360, 70));

        text3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text3.setText("Number Of Booked tickets");
        getContentPane().add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 250, 40));
        getContentPane().add(numberofbookedtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 370, 80));

        main2label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainticketingsystem/4.jpg"))); // NOI18N
        getContentPane().add(main2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        setBounds(0, 0, 1296, 839);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
          Ticketdetails tds = new Ticketdetails();
          tds.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        
           Passengerdetail aPassengerdetail =new Passengerdetail(nametext.getText(),Integer.parseInt(IDtext.getText()),Integer.parseInt(trainidtext.getText()),Integer.parseInt(numberofbookedtext.getText()));
        try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aPassengerdetail);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Passengerdetail.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "ok");     
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void viewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttonActionPerformed
        // TODO add your handling code here:
        Passengerview pv = new Passengerview();
        pv.setVisible(true);
    }//GEN-LAST:event_viewbuttonActionPerformed

    private void updatebittonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebittonActionPerformed
        // TODO add your handling code here:
        String sql = "update passengerdetails set passengername = ? ,  trainid = ? , numberofbookedtickets = ? where passengerid = ?";
        try
        {
            System.out.println("  yaay :3 ...");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=9803;" +
            "databaseName=TrainTicketingSystem;";
                 con = DriverManager.getConnection(connectionUrl);
                 pst = con.prepareStatement(sql);
                 pst.setString(1,nametext.getText());
                
                 pst.setString(2,trainidtext.getText());
                 pst.setString(3,numberofbookedtext.getText());
                 pst.setString(4,IDtext.getText());
                 
                 pst.executeUpdate();
                
                
                 
                  JOptionPane.showMessageDialog(this, "Updated!!!");
                 
                 
                 
                       
        }
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(this, "not updated");
                    
                }
    }//GEN-LAST:event_updatebittonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
         String sql = "delete from passengerdetails where  passengerid= ?";
        try
        {
            System.out.println("  yaay :3 ...");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=9803;" +
            "databaseName=TrainTicketingSystem;";
                 con = DriverManager.getConnection(connectionUrl);
                 pst = con.prepareStatement(sql);
                 pst.setString(1,IDtext.getText());
                 
                 pst.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Deleted!!!");
                 
                 
                 
                       
        }
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(this, "Not Deleted");
                    
                }
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengerdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDlabel;
    private javax.swing.JTextField IDtext;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel main2label;
    private javax.swing.JLabel mainlabel;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField numberofbookedtext;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel textlabel;
    private javax.swing.JTextField trainidtext;
    private javax.swing.JButton updatebitton;
    private javax.swing.JButton viewbutton;
    // End of variables declaration//GEN-END:variables
}
