/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticketingsystem;

import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trainticketingsystem.otherjavas.Operationpassenger;
import trainticketingsystem.otherjavas.Passengerdetail;

/**
 *
 * @author Mila
 */
public class Tickets extends javax.swing.JFrame {
    

    /**
     * Creates new form Tickets
     */
    public Tickets() {
        initComponents();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJlabel = new javax.swing.JLabel();
        labelfrom = new javax.swing.JLabel();
        fromchoice = new javax.swing.JComboBox();
        text2label = new javax.swing.JLabel();
        tochoice = new javax.swing.JComboBox();
        text3label = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        datelabel = new javax.swing.JLabel();
        text4label = new javax.swing.JLabel();
        text1Jlabel = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        text5label = new javax.swing.JLabel();
        donebutton = new javax.swing.JButton();
        textfield3 = new javax.swing.JTextField();
        text6label = new javax.swing.JLabel();
        classchoice = new javax.swing.JComboBox();
        infolabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ticketnumlabel = new javax.swing.JLabel();
        ticketbookedtext = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        main2label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainJlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(mainJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -30, 1280, 800));

        labelfrom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("From");
        getContentPane().add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 102, 60, 30));

        fromchoice.setBackground(new java.awt.Color(153, 153, 153));
        fromchoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dhaka", "Chittagong", "Sylhet" }));
        getContentPane().add(fromchoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 30));

        text2label.setBackground(new java.awt.Color(255, 255, 255));
        text2label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text2label.setForeground(new java.awt.Color(255, 255, 255));
        text2label.setText("To");
        getContentPane().add(text2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 30, 30));

        tochoice.setBackground(new java.awt.Color(153, 153, 153));
        tochoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(tochoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 200, 30));

        text3label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text3label.setForeground(new java.awt.Color(255, 255, 255));
        text3label.setText("Date");
        getContentPane().add(text3label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 30));
        getContentPane().add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 240, 50));

        datelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 255, 255));
        datelabel.setText(" YY-MM-DD");
        getContentPane().add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 240, 90, -1));

        text4label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text4label.setForeground(new java.awt.Color(255, 255, 255));
        text4label.setText("Train ID");
        getContentPane().add(text4label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, 20));

        text1Jlabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        text1Jlabel.setForeground(new java.awt.Color(255, 255, 255));
        text1Jlabel.setText("    Ticket Booking");
        getContentPane().add(text1Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 370, 40));

        text5.setText(" ");
        text5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text5ActionPerformed(evt);
            }
        });
        getContentPane().add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 240, 50));

        text5label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text5label.setForeground(new java.awt.Color(255, 255, 255));
        text5label.setText(" Passenger Name");
        getContentPane().add(text5label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 210, 50));

        donebutton.setBackground(new java.awt.Color(255, 255, 255));
        donebutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        donebutton.setText("Booked!\n\n");
        donebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(donebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 303, 140, 50));

        textfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield3ActionPerformed(evt);
            }
        });
        getContentPane().add(textfield3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 290, 50));

        text6label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text6label.setForeground(new java.awt.Color(255, 255, 255));
        text6label.setText("Class");
        getContentPane().add(text6label, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 100, 80, 30));

        classchoice.setBackground(new java.awt.Color(153, 153, 153));
        classchoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(classchoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 200, 30));

        infolabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        infolabel.setForeground(new java.awt.Color(255, 255, 255));
        infolabel.setText("   Details Information");
        getContentPane().add(infolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 454, 290, 70));

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Passenger Name", "Passenger ID", "Train ID", "Ticket Number", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 790, 90));

        ticketnumlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ticketnumlabel.setForeground(new java.awt.Color(255, 255, 255));
        ticketnumlabel.setText("Number Of Ticket");
        getContentPane().add(ticketnumlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 170, 50));
        getContentPane().add(ticketbookedtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 130, 40));

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backbutton.setText("Back To Train Info");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 340, 50));

        main2label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainticketingsystem/6.jpg"))); // NOI18N
        getContentPane().add(main2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield3ActionPerformed

    private void text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text5ActionPerformed

    private void donebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donebuttonActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_donebuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here;     
        Trains tr = new Trains();
        tr.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JComboBox classchoice;
    private javax.swing.JLabel datelabel;
    private javax.swing.JButton donebutton;
    private javax.swing.JComboBox fromchoice;
    private javax.swing.JLabel infolabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JLabel main2label;
    private javax.swing.JLabel mainJlabel;
    private javax.swing.JLabel text1Jlabel;
    private javax.swing.JLabel text2label;
    private javax.swing.JLabel text3label;
    private javax.swing.JTextField text4;
    private javax.swing.JLabel text4label;
    private javax.swing.JTextField text5;
    private javax.swing.JLabel text5label;
    private javax.swing.JLabel text6label;
    private javax.swing.JTextField textfield3;
    private javax.swing.JTextField ticketbookedtext;
    private javax.swing.JLabel ticketnumlabel;
    private javax.swing.JComboBox tochoice;
    // End of variables declaration//GEN-END:variables
}
