/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticketingsystem;


/**
 *
 * @author Mila
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trainticketingsystem.otherjavas.Ticketdetail;
import trainticketingsystem.otherjavas.Operationticket;


public class Ticketdetails extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Ticketdetails
     */
    
    Operationticket   ope = new Operationticket();
    ArrayList <Ticketdetails> Ticketdetailslist =new ArrayList <Ticketdetails>();//changes done here 
    
    public Ticketdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainlabel = new javax.swing.JLabel();
        textlabel = new javax.swing.JLabel();
        Idlabel = new javax.swing.JLabel();
        Idtext = new javax.swing.JTextField();
        ticketidlabel = new javax.swing.JLabel();
        ticketidtext = new javax.swing.JTextField();
        pricelabel = new javax.swing.JLabel();
        pricetext = new javax.swing.JTextField();
        classlabel = new javax.swing.JLabel();
        classtext = new javax.swing.JTextField();
        nextbutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        viewbutton = new javax.swing.JButton();
        main2label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        textlabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textlabel.setText(" Ticket Details");
        getContentPane().add(textlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 290, 50));

        Idlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Idlabel.setText("Train ID");
        getContentPane().add(Idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 80, 40));

        Idtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdtextActionPerformed(evt);
            }
        });
        getContentPane().add(Idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 310, 70));

        ticketidlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ticketidlabel.setText("Ticket ID");
        getContentPane().add(ticketidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 302, 90, 40));
        getContentPane().add(ticketidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 310, 80));

        pricelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pricelabel.setText("Price");
        getContentPane().add(pricelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 424, 80, 40));
        getContentPane().add(pricetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 310, 80));

        classlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        classlabel.setText("Class");
        getContentPane().add(classlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 544, 70, 30));
        getContentPane().add(classtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 310, 80));

        nextbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nextbutton.setText("Next\n");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(nextbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 220, 60));

        addbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addbutton.setText("Add\n");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 220, 60));

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updatebutton.setText("Update\n");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 220, 60));

        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deletebutton.setText("Delete ");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 220, 60));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backbutton.setText("Back ");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 463, 220, 60));

        viewbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewbutton.setText("View");
        viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(viewbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 220, 60));

        main2label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainticketingsystem/9.jpg"))); // NOI18N
        getContentPane().add(main2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
         Traindetails td = new Traindetails();
          td.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        // TODO add your handling code here:
          Passengerdetails pd = new Passengerdetails();
          pd.setVisible(true);
    }//GEN-LAST:event_nextbuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
           Ticketdetail aTicketdetail = new Ticketdetail(Integer.parseInt(Idtext.getText()),Integer.parseInt(ticketidtext.getText()),Integer.parseInt(pricetext.getText()),classtext.getText());
           
            try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aTicketdetail);
        } 
            catch (ClassNotFoundException ex)
            {
            Logger.getLogger(Ticketdetail.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "ok");   
        
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void IdtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdtextActionPerformed

    private void viewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttonActionPerformed
        // TODO add your handling code here:
        
        Ticketview tv = new Ticketview();
        tv.setVisible(true);
    }//GEN-LAST:event_viewbuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling 
        String sql = "update ticketdetails set ticketid = ? ,  price  = ? , class = ? where trainid = ?";
        try
        {
            System.out.println("  yaay :3 ...");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=9803;" +
            "databaseName=TrainTicketingSystem;";
                 con = DriverManager.getConnection(connectionUrl);
                 pst = con.prepareStatement(sql);
                 pst.setString(1,ticketidtext.getText());
                
                 pst.setString(2,pricetext.getText());
                 pst.setString(3,classtext.getText());
                 pst.setString(4,Idtext.getText());
                 
                 pst.executeUpdate();
                
                
                 
                  JOptionPane.showMessageDialog(this, "Updated!!!");
                 
                 
                 
                       
        }
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(this, "Not updated");
                    
                }
         
        
     
        
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        
         String sql = "delete from ticketdetails where trainid = ?";
        try
        {
            System.out.println("  yaay :3 ...");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=9803;" +
            "databaseName=TrainTicketingSystem;";
                 con = DriverManager.getConnection(connectionUrl);
                 pst = con.prepareStatement(sql);
                 pst.setString(1,Idtext.getText());
                 
                 pst.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Deleted!!!");
                 
                 
                 
                       
        }
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(this, "Not Deleted");
                    
                }
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticketdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticketdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticketdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticketdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticketdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Idlabel;
    private javax.swing.JTextField Idtext;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel classlabel;
    private javax.swing.JTextField classtext;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel main2label;
    private javax.swing.JLabel mainlabel;
    private javax.swing.JButton nextbutton;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JTextField pricetext;
    private javax.swing.JLabel textlabel;
    private javax.swing.JLabel ticketidlabel;
    private javax.swing.JTextField ticketidtext;
    private javax.swing.JButton updatebutton;
    private javax.swing.JButton viewbutton;
    // End of variables declaration//GEN-END:variables
}
