/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticketingsystem;



import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trainticketingsystem.otherjavas.Traindetail;
import trainticketingsystem.otherjavas.Operationtrain;

/**
 *
 * @author Mila
 */
public class Traindetails extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Traindetails
     */
     Operationtrain   ope = new Operationtrain();
     ArrayList <Traindetails> TraindetailsList=new ArrayList <Traindetails>();//changes done here 
     
     
    public Traindetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Idlabel = new javax.swing.JLabel();
        IDtext = new javax.swing.JTextField();
        quantitylabel = new javax.swing.JLabel();
        quantitytext = new javax.swing.JTextField();
        sourcelabel = new javax.swing.JLabel();
        sourcetext = new javax.swing.JTextField();
        destinationlabel = new javax.swing.JLabel();
        destinationtext = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        nextbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        datelabel = new javax.swing.JLabel();
        datetext = new javax.swing.JTextField();
        viewbutton = new javax.swing.JButton();
        main2label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("        Train Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 350, 80));

        Idlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Idlabel.setText("Train ID");
        getContentPane().add(Idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 100, 40));

        IDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtextActionPerformed(evt);
            }
        });
        getContentPane().add(IDtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 250, 60));

        quantitylabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quantitylabel.setText("Quantity Of Ticket");
        getContentPane().add(quantitylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 170, 60));

        quantitytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytextActionPerformed(evt);
            }
        });
        getContentPane().add(quantitytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 250, 70));

        sourcelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sourcelabel.setText("Source Station");
        getContentPane().add(sourcelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 364, -1, 50));
        getContentPane().add(sourcetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 250, 70));

        destinationlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        destinationlabel.setText("Destination Station");
        getContentPane().add(destinationlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 472, 180, 60));
        getContentPane().add(destinationtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 250, 70));

        addbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 220, 60));

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 220, 60));

        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 323, 220, 60));

        nextbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nextbutton.setText("Next");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(nextbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 220, 60));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 563, 220, 60));

        datelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        datelabel.setText("Date");
        getContentPane().add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 60, 50));
        getContentPane().add(datetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 250, 70));

        viewbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewbutton.setText("View");
        viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(viewbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 220, 60));

        main2label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainticketingsystem/9.jpg"))); // NOI18N
        getContentPane().add(main2label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
          Admindetails ads = new Admindetails();
          ads.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        // TODO add your handling code here:
          Ticketdetails tds = new Ticketdetails();
          tds.setVisible(true);
    }//GEN-LAST:event_nextbuttonActionPerformed

    private void IDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtextActionPerformed

    private void quantitytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytextActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here: update done here
        
        String sql = "update traindetails set quantity = ? ,sourcestation = ? ,destinationstation = ? ,ticketdate =? where trainid = ?";
        try
        {
            System.out.println("  yaay :3 ...");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=9803;" +
            "databaseName=TrainTicketingSystem;";
                 con = DriverManager.getConnection(connectionUrl);
                 pst = con.prepareStatement(sql);
                 pst.setString(1,quantitytext.getText());
                
                 pst.setString(2,sourcetext.getText());
                 pst.setString(3,destinationtext.getText());
                 pst.setString(4,datetext.getText());
                 pst.setString(5,IDtext.getText());
                 
                 pst.executeUpdate();
                
                
                 
                  JOptionPane.showMessageDialog(this, "Updated!!!");
                 
                 
                 
                       
        }
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(this, "Not updated");
                    
                }
       
      
        
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here: add here
           Traindetail aTraindetail = new Traindetail(Integer.parseInt(IDtext.getText()),Integer.parseInt(quantitytext.getText()),sourcetext.getText(),destinationtext.getText(),datetext.getText());
           
            try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aTraindetail);
        } 
            catch (ClassNotFoundException ex)
            {
            Logger.getLogger(Traindetail.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "ok");   
           
           
    }//GEN-LAST:event_addbuttonActionPerformed

    private void viewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttonActionPerformed
        // TODO add your handling code here:
        
        Trainview tvd = new Trainview();
        tvd.setVisible(true);
    }//GEN-LAST:event_viewbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        
          String sql = "delete from traindetails where trainid = ?";
        try
        {
            System.out.println("  yaay :3 ...");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=9803;" +
            "databaseName=TrainTicketingSystem;";
                 con = DriverManager.getConnection(connectionUrl);
                 pst = con.prepareStatement(sql);
                 pst.setString(1,IDtext.getText());
                 
                 pst.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Deleted!!!");
                 
                 
                 
                       
        }
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(this, "Not Deleted");
                    
                }
       
        
        
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traindetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traindetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traindetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traindetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traindetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtext;
    private javax.swing.JLabel Idlabel;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField datetext;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel destinationlabel;
    private javax.swing.JTextField destinationtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel main2label;
    private javax.swing.JLabel mainlabel;
    private javax.swing.JButton nextbutton;
    private javax.swing.JLabel quantitylabel;
    private javax.swing.JTextField quantitytext;
    private javax.swing.JLabel sourcelabel;
    private javax.swing.JTextField sourcetext;
    private javax.swing.JButton updatebutton;
    private javax.swing.JButton viewbutton;
    // End of variables declaration//GEN-END:variables
}
